### ISSUE TITLE
Non-existent service "templating.engine.php".

### ISSUE THREAD

**Issue by TuemmlerKon** [MWSimple/CrudGeneratorBundle#10]
I got this error while trying to install the CrudGeneratorBundle:

```
"The service "knp_paginator.templating.helper.pagination" has a dependency on a non-existent service "templating.engine.php"."
```

I found out that the problem was fixed by KnpMenuBundle in [3f00050cfbed246bb6f195ebee6badb50190fcf6](https://github.com/KnpLabs/KnpPaginatorBundle/commit/3f00050cfbed246bb6f195ebee6badb50190fcf6) so perhaps you should update your dependencies?

**Comment by gonzaloalonsod** [comment]
https://github.com/MWSimple/CrudGeneratorBundle/commit/ad07a80a557fc1f72d478738a271262d47d6d93b
